site_name: Typeregistry Documentation
theme:
  name: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
nav:
  - Home: index.md
  - Creating Data Types:
    - Navigation and Authentication: creatingTypes/ui_auth.md
    - The Different Data Types: creatingTypes/types.md
    - Type Creation: creatingTypes/typeCreation.md
    - Managing Access Control: creatingTypes/acl.md
    - Schema Generation and Validating Data: creatingTypes/validation.md
  - Tutorials:
    - Cordra API Tutorial: Tutorials/apiIntro.md
    - Recreating an existing Schema: Tutorials/recreateSchema.md
  - Schemas:
    - Overview: schemas/Overview.md
    - Basic Types: schemas/basictype.md
    - Info Types: schemas/infotype.md
    - Taxonomy Nodes: schemas/taxonomynode.md
    - Measurement Units: schemas/measurementunit.md